name: Run Script with Time-Based Scheduling

on:
  schedule:
    - cron: "*/5 6-21 * * *"  # Every 5 minutes from 6 AM to 9:55 PM
    - cron: "*/30 22-23,0-5 * * *"  # Every 30 minutes from 10 PM to 5:30 AM
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the Script
        env:
          SECRET_1: ${{ secrets.SECRET_1 }}
          SECRET_2: ${{ secrets.SECRET_2 }}
          SECRET_3: ${{ secrets.SECRET_3 }}
          SECRET_4: ${{ secrets.SECRET_4 }}
        run: |
          echo "Running script with secrets..."
          python runner.py
