name: Notify on Booking Event

on:
  schedule:
    - cron: "*/5 12-23,0-2 * * *"  # Runs every 5 minutes from 7 AM to 8:55 PM
    - cron: "*/30 2-11 * * *"  # Runs every 30 minutes from 9 PM to 6:30 AM
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the Script
        env:
          BOOKING_URL: ${{ secrets.BOOKING_URL }}
          SPORTS_URL: ${{ secrets.SPORTS_URL }}
          FITNESS_URL: ${{ secrets.FITNESS_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          DISCORD_POSTS: ${{ secrets.DISCORD_POSTS }}
          DISCORD_LOGS: ${{ secrets.DISCORD_LOGS }}
          DISCORD_UID: ${{ secrets.DISCORD_UID }}
        run: |
          echo "Running script with secrets..."
          python github_runner.py
