name: Notify on Booking Event

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the Script
        env:
          BOOKING_URL: ${{ secrets.BOOKING_URL }}
          SPORTS_URL: ${{ secrets.SPORTS_URL }}
          FITNESS_URL: ${{ secrets.FITNESS_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          DISCORD_POSTS: ${{ secrets.DISCORD_POSTS }}
          DISCORD_LOGS: ${{ secrets.DISCORD_LOGS }}
          DISCORD_UID: ${{ secrets.DISCORD_UID }}
        run: |
          echo "Running script with secrets..."
          python github_runner.py
